{"timestamp":1748463656134,"host":"hivenode02","text":"python: --- ***** -----","label":"normal"}
{"timestamp":1748467719424,"host":"hivenode02","text":"python: - ** ---------- .> app:         __main__:0x1d3aa90","label":"normal"}
{"timestamp":1748467792918,"host":"hivenode02","text":"python: -- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)","label":"normal"}
{"timestamp":1748469189574,"host":"hivenode02","text":"systemd: Starting Infinity Celery Worker Service...","label":"normal"}
{"timestamp":1748469643243,"host":"hivenode02","text":"xinetd[4580]: START: mongo_status pid=3302714 from=::ffff:10.108.196.201","label":"normal"}
{"timestamp":1748470123060,"host":"hivenode02","text":"systemd: Started Session 2170481 of user root.","label":"normal"}
{"timestamp":1748471062763,"host":"hivenode02","text":"systemd: Starting Session 2171089 of user root.","label":"normal"}
{"timestamp":1748471279048,"host":"hivenode02","text":"xinetd[4580]: START: mysql_status pid=1381544 from=::ffff:10.108.196.205","label":"normal"}
{"timestamp":1748472533174,"host":"hivenode02","text":"systemd: infi-celery.service: main process exited, code=exited, status=1\/FAILURE","label":"normal"}
{"timestamp":1748472718009,"host":"hivenode02","text":"python: absolutely not recommended!","label":"normal"}
{"timestamp":1748475350405,"host":"hivenode02","text":"python: -- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)","label":"normal"}
{"timestamp":1748476439120,"host":"hivenode02","text":"xinetd[4580]: START: zk_status pid=70104 from=::ffff:10.108.196.204","label":"normal"}
{"timestamp":1748477059305,"host":"hivenode02","text":"systemd-logind: Removed session 2174920.","label":"normal"}
{"timestamp":1748480305296,"host":"hivenode02","text":"systemd: Started Session 2176969 of user root.","label":"normal"}
{"timestamp":1748480361325,"host":"hivenode02","text":"systemd: Starting Infinity Celery Worker Service...","label":"normal"}
{"timestamp":1748480557369,"host":"hivenode02","text":"xinetd[4580]: EXIT: mysql_status status=0 pid=1504870 duration=1(sec)","label":"normal"}
{"timestamp":1748481645380,"host":"hivenode02","text":"python: - ** ---------- .> results:     elasticsearch:\/\/10.0.100.105:8200\/infi_queue_result\/queue_result","label":"normal"}
{"timestamp":1748481935720,"host":"hivenode02","text":"systemd: Unit infi-celery.service entered failed state.","label":"normal"}
{"timestamp":1748482349074,"host":"hivenode02","text":"python: [tasks]","label":"normal"}
{"timestamp":1748482805402,"host":"hivenode02","text":"systemd: Starting Session 2178563 of user root.","label":"normal"}
{"timestamp":1748482915382,"host":"hivenode02","text":"xinetd[4580]: START: mongo_status pid=558304 from=::ffff:10.108.196.203","label":"normal"}
{"timestamp":1748483225363,"host":"hivenode02","text":"python: --- * ***  * -- Linux-3.10.0-1160.el7.x86_64-x86_64-with-centos-7.4.1708-Core 2025-05-29 09:47:04","label":"normal"}
{"timestamp":1748486421885,"host":"hivenode02","text":"systemd: Started Session 2180872 of user root.","label":"normal"}
{"timestamp":1748487437997,"host":"hivenode02","text":"systemd-logind: New session 2181513 of user root.","label":"normal"}
{"timestamp":1748487521435,"host":"hivenode02","text":"python: User information: uid=0 euid=0 gid=0 egid=0","label":"normal"}
{"timestamp":1748488029681,"host":"hivenode02","text":"python: . infinity.task.tasks.infi_cluster","label":"normal"}
{"timestamp":1748488979431,"host":"hivenode02","text":"python: [tasks]","label":"normal"}
{"timestamp":1748489563072,"host":"hivenode02","text":"systemd-logind: New session 2182867 of user root.","label":"normal"}
{"timestamp":1748489658464,"host":"hivenode02","text":"python: User information: uid=0 euid=0 gid=0 egid=0","label":"normal"}
{"timestamp":1748491340251,"host":"hivenode02","text":"systemd: infi-celery.service failed.","label":"normal"}
{"timestamp":1748492596225,"host":"hivenode02","text":"python: \/usr\/lib\/python2.7\/site-packages\/celery\/platforms.py:796: RuntimeWarning: You're running the worker with superuser privileges: this is","label":"normal"}
{"timestamp":1748493169294,"host":"hivenode02","text":"python: .> infinity_queue   exchange=infinity_exchange(direct) key=infinity_queue","label":"normal"}
{"timestamp":1748495897289,"host":"hivenode02","text":"xinetd[4580]: EXIT: mysql_status status=0 pid=1615580 duration=1(sec)","label":"normal"}
{"timestamp":1748495994333,"host":"hivenode02","text":"xinetd[4580]: START: mysql_status pid=1757339 from=::ffff:10.108.196.204","label":"normal"}
{"timestamp":1748498303389,"host":"hivenode02","text":"systemd-logind: Removed session 2188455.","label":"normal"}
{"timestamp":1748498395824,"host":"hivenode02","text":"xinetd[4580]: EXIT: mysql_status status=0 pid=887986 duration=0(sec)","label":"normal"}
{"timestamp":1748499238044,"host":"hivenode02","text":"xinetd[4580]: START: mongo_status pid=2051286 from=::ffff:10.108.196.205","label":"normal"}
{"timestamp":1748499696262,"host":"hivenode02","text":"python: --- * ***  * -- Linux-3.10.0-1160.el7.x86_64-x86_64-with-centos-7.4.1708-Core 2025-05-29 14:21:35","label":"normal"}
{"timestamp":1748499970245,"host":"hivenode02","text":"infinity[3036237]: start monitor trigger: ntpd","label":"normal"}
{"timestamp":1748501057879,"host":"hivenode02","text":"python: - ** ---------- [config]","label":"normal"}
{"timestamp":1748501191941,"host":"hivenode02","text":"xinetd[4580]: EXIT: zk_status status=0 pid=542471 duration=0(sec)","label":"normal"}
{"timestamp":1748502426278,"host":"hivenode02","text":"systemd: Started Session 2191079 of user root.","label":"normal"}
{"timestamp":1748503789819,"host":"hivenode02","text":"bash: WARNING: 2025\/05\/29 15:29:49 grpc: Server.Serve failed to create ServerTransport:  connection error: desc = \"transport: http2Server.HandleStreams failed to read initial settings frame: read tcp 10.0.100.102:2379->10.0.100.102:54853: read: connection reset by peer\"","label":"abnormal"}
{"timestamp":1748504398941,"host":"hivenode02","text":"systemd: infi-celery.service: main process exited, code=exited, status=1\/FAILURE","label":"normal"}
{"timestamp":1748504901784,"host":"hivenode02","text":"systemd: Starting Session 2192651 of user root.","label":"normal"}
{"timestamp":1748504912600,"host":"hivenode02","text":"python: - ** ---------- .> transport:   amqp:\/\/rabbitmq:**@10.0.100.105:5672\/\/","label":"normal"}
{"timestamp":1748506257990,"host":"hivenode02","text":"xinetd[4580]: EXIT: mongo_status status=0 pid=3334454 duration=0(sec)","label":"normal"}
{"timestamp":1748506616154,"host":"hivenode02","text":"infinity[3036237]: an error occurred while requesting bindings <urlopen error [Errno 111] Connection refused>","label":"abnormal"}
{"timestamp":1748508643432,"host":"hivenode02","text":"python: - ** ---------- [config]","label":"normal"}
{"timestamp":1748508741653,"host":"hivenode02","text":"systemd: Started Session 2195157 of user root.","label":"normal"}
{"timestamp":1748510156622,"host":"hivenode02","text":"python: -- * - **** ---","label":"normal"}
{"timestamp":1748510664210,"host":"hivenode02","text":"systemd: Unit infi-celery.service entered failed state.","label":"normal"}
{"timestamp":1748511392447,"host":"hivenode02","text":"xinetd[4580]: EXIT: mongo_status status=0 pid=2103765 duration=0(sec)","label":"normal"}
{"timestamp":1748512372072,"host":"hivenode02","text":"systemd: infi-celery.service holdoff time over, scheduling restart.","label":"normal"}
{"timestamp":1748512431422,"host":"hivenode02","text":"python: --- ***** -----","label":"normal"}
{"timestamp":1748512808450,"host":"hivenode02","text":"systemd: Unit infi-celery.service entered failed state.","label":"normal"}
{"timestamp":1748514347836,"host":"hivenode02","text":"systemd: Starting Session 2198808 of user root.","label":"normal"}
{"timestamp":1748516401395,"host":"hivenode02","text":"python: .> infinity_queue   exchange=infinity_exchange(direct) key=infinity_queue","label":"normal"}
{"timestamp":1748518191348,"host":"hivenode02","text":"xinetd[4580]: START: zk_status pid=3182160 from=::ffff:10.108.196.204","label":"normal"}
{"timestamp":1748518773050,"host":"hivenode02","text":"xinetd[4580]: START: mysql_status pid=3993484 from=::ffff:10.108.196.201","label":"normal"}
{"timestamp":1748519261001,"host":"hivenode02","text":"systemd-logind: New session 2201977 of user root.","label":"normal"}
{"timestamp":1748519808445,"host":"hivenode02","text":"xinetd[4580]: EXIT: mongo_status status=0 pid=1249807 duration=0(sec)","label":"normal"}
{"timestamp":1748520187152,"host":"hivenode02","text":"infinity[3036237]: an error occurred while requesting bindings <urlopen error [Errno 111] Connection refused>","label":"abnormal"}
{"timestamp":1748522545929,"host":"hivenode02","text":"python: -------------- [queues]","label":"normal"}
{"timestamp":1748524403822,"host":"hivenode02","text":"systemd: infi-celery.service holdoff time over, scheduling restart.","label":"normal"}
{"timestamp":1748526122307,"host":"hivenode02","text":"bash: WARNING: 2025\/05\/29 21:42:02 grpc: Server.Serve failed to create ServerTransport:  connection error: desc = \"transport: http2Server.HandleStreams failed to read initial settings frame: read tcp 10.0.100.102:2379->10.0.100.106:65458: read: connection reset by peer\"","label":"abnormal"}
{"timestamp":1748526486402,"host":"hivenode02","text":"xinetd[4580]: EXIT: zk_status status=0 pid=2108196 duration=0(sec)","label":"normal"}
{"timestamp":1748527781195,"host":"hivenode02","text":"python: -- * - **** ---","label":"normal"}
{"timestamp":1748528031811,"host":"hivenode02","text":"infinity[3036237]: an error occurred while requesting bindings <urlopen error [Errno 111] Connection refused>","label":"abnormal"}
{"timestamp":1748528150647,"host":"hivenode02","text":"python: --- ***** -----","label":"normal"}
{"timestamp":1748528736833,"host":"hivenode02","text":"python: .> infinity_queue   exchange=infinity_exchange(direct) key=infinity_queue","label":"normal"}
{"timestamp":1748528936517,"host":"hivenode02","text":"infinity[3036237]: an error occurred while requesting bindings <urlopen error [Errno 111] Connection refused>","label":"abnormal"}
{"timestamp":1748530146686,"host":"hivenode02","text":"infinity[3036237]: an error occurred while requesting bindings <urlopen error [Errno 111] Connection refused>","label":"abnormal"}
{"timestamp":1748530146687,"host":"hivenode02","text":"infinity[3036237]: an error occurred while requesting bindings <urlopen error [Errno 111] Connection refused>","label":"abnormal"}
{"timestamp":1748530659067,"host":"hivenode02","text":"systemd: Starting Session 2209322 of user root.","label":"normal"}
{"timestamp":1748531059450,"host":"hivenode02","text":"xinetd[4580]: EXIT: zk_status status=0 pid=98525 duration=0(sec)","label":"normal"}
{"timestamp":1748531184182,"host":"hivenode02","text":"python: . infinity.task.tasks.infi_cluster","label":"normal"}
{"timestamp":1748533207257,"host":"hivenode02","text":"systemd: infi-celery.service failed.","label":"normal"}
{"timestamp":1748534202460,"host":"hivenode02","text":"xinetd[4580]: EXIT: mongo_status status=0 pid=276335 duration=0(sec)","label":"normal"}
{"timestamp":1748534366608,"host":"hivenode02","text":"python: .> node2            exchange=node2(direct) key=node2","label":"normal"}
{"timestamp":1748534401397,"host":"hivenode02","text":"kernel: smartord[3636642]: segfault at 7f2ef5a59880 ip 00007f2ef40954bc sp 00007ffd7f41a720 error 4 in libc-2.17.so[7f2ef4015000+1c4000]","label":"abnormal"}
{"timestamp":1748534706026,"host":"hivenode02","text":"xinetd[4580]: START: mongo_status pid=973993 from=::ffff:10.108.196.205","label":"normal"}
{"timestamp":1748536981673,"host":"hivenode02","text":"systemd: Starting Session 2213387 of user root.","label":"normal"}
{"timestamp":1748537925796,"host":"hivenode02","text":"python: - ** ---------- .> app:         __main__:0x15aba90","label":"normal"}
{"timestamp":1748538064221,"host":"hivenode02","text":"systemd: infi-celery.service: main process exited, code=exited, status=1\/FAILURE","label":"normal"}
{"timestamp":1748538107752,"host":"hivenode02","text":"kill: kill: cannot find process \"\"","label":"normal"}
{"timestamp":1748540704139,"host":"hivenode02","text":"infinity[3036237]: an error occurred while requesting bindings <urlopen error [Errno 111] Connection refused>","label":"abnormal"}
{"timestamp":1748541608898,"host":"hivenode02","text":"infinity[3036237]: an error occurred while requesting bindings <urlopen error [Errno 111] Connection refused>","label":"abnormal"}
{"timestamp":1748542225855,"host":"hivenode02","text":"python: [tasks]","label":"normal"}
{"timestamp":1748543574965,"host":"hivenode02","text":"systemd: infi-celery.service: main process exited, code=exited, status=1\/FAILURE","label":"normal"}
{"timestamp":1748544181324,"host":"hivenode02","text":"systemd: Started Infinity Celery Worker Service.","label":"normal"}
{"timestamp":1748544936793,"host":"hivenode02","text":"xinetd[4580]: START: mysql_status pid=2475340 from=::ffff:10.108.196.202","label":"normal"}
{"timestamp":1748544984379,"host":"hivenode02","text":"infinity[8164]: an error occurred while requesting bindings <urlopen error [Errno 111] Connection refused>","label":"abnormal"}
{"timestamp":1748546074207,"host":"hivenode02","text":"xinetd[4580]: START: zk_status pid=4019414 from=::ffff:10.108.196.202","label":"normal"}
{"timestamp":1748546274608,"host":"hivenode02","text":"systemd: Started Session 2219401 of user root.","label":"normal"}
{"timestamp":1748546660431,"host":"hivenode02","text":"python: - ** ---------- [config]","label":"normal"}
{"timestamp":1748547370658,"host":"hivenode02","text":"python: - ** ---------- .> results:     elasticsearch:\/\/10.0.100.105:8200\/infi_queue_result\/queue_result","label":"normal"}
{"timestamp":1748547592313,"host":"hivenode02","text":"systemd: Starting Session 2220241 of user root.","label":"normal"}
{"timestamp":1748550598612,"host":"hivenode02","text":"xinetd[4580]: START: zk_status pid=1853304 from=::ffff:10.108.196.201","label":"normal"}
{"timestamp":1748551542855,"host":"hivenode02","text":"systemd: Starting Session 2222761 of user root.","label":"normal"}
{"timestamp":1748552514162,"host":"hivenode02","text":"python: --- ***** -----","label":"normal"}
{"timestamp":1748552579409,"host":"hivenode02","text":"python: -------------- [queues]","label":"normal"}
{"timestamp":1748555680297,"host":"hivenode02","text":"systemd: Started Session 2225406 of user root.","label":"normal"}
{"timestamp":1748555766537,"host":"hivenode02","text":"python: absolutely not recommended!","label":"normal"}
{"timestamp":1748555847394,"host":"hivenode02","text":"infinity[8164]: an error occurred while requesting bindings <urlopen error [Errno 111] Connection refused>","label":"abnormal"}
{"timestamp":1748556149058,"host":"hivenode02","text":"infinity[8164]: an error occurred while requesting bindings <urlopen error [Errno 111] Connection refused>","label":"abnormal"}
{"timestamp":1748556917947,"host":"hivenode02","text":"python: \/usr\/lib\/python2.7\/site-packages\/celery\/platforms.py:796: RuntimeWarning: You're running the worker with superuser privileges: this is","label":"normal"}
{"timestamp":1748557180354,"host":"hivenode02","text":"xinetd[4580]: EXIT: zk_status status=0 pid=2529741 duration=0(sec)","label":"normal"}
{"timestamp":1748557617108,"host":"hivenode02","text":"xinetd[4580]: START: mysql_status pid=3108075 from=::ffff:10.108.196.204","label":"normal"}
{"timestamp":1748558376964,"host":"hivenode02","text":"python: . infinity.task.tasks.infi_cluster","label":"normal"}
{"timestamp":1748558863483,"host":"hivenode02","text":"kill: kill: cannot find process \"\"","label":"normal"}
{"timestamp":1748559149500,"host":"hivenode02","text":"xinetd[4580]: EXIT: mongo_status status=0 pid=1029450 duration=0(sec)","label":"normal"}
{"timestamp":1748559507439,"host":"hivenode02","text":"python: - ** ---------- [config]","label":"normal"}
{"timestamp":1748560115672,"host":"hivenode02","text":"python: -------------- celery@hivenode02 v4.2.1 (windowlicker)","label":"normal"}
{"timestamp":1748561865051,"host":"hivenode02","text":"systemd: Started Session 2229360 of user root.","label":"normal"}
{"timestamp":1748562157745,"host":"hivenode02","text":"kill: kill: cannot find process \"\"","label":"normal"}
{"timestamp":1748562648740,"host":"hivenode02","text":"systemd-logind: New session 2229865 of user root.","label":"normal"}
{"timestamp":1748563731927,"host":"hivenode02","text":"systemd: Started Session 2230566 of user root.","label":"normal"}
{"timestamp":1748565703240,"host":"hivenode02","text":"xinetd[4580]: EXIT: zk_status status=0 pid=1637711 duration=0(sec)","label":"normal"}
{"timestamp":1748565793008,"host":"hivenode02","text":"kill: kill: cannot find process \"\"","label":"normal"}
{"timestamp":1748566722351,"host":"hivenode02","text":"xinetd[4580]: START: mysql_status pid=3022841 from=::ffff:10.108.196.203","label":"normal"}
{"timestamp":1748567567082,"host":"hivenode02","text":"infinity[8164]: monitor net list is null","label":"normal"}
{"timestamp":1748568702748,"host":"hivenode02","text":"python: absolutely not recommended!","label":"normal"}
{"timestamp":1748569066118,"host":"hivenode02","text":"python: - ** ---------- .> transport:   amqp:\/\/rabbitmq:**@10.0.100.105:5672\/\/","label":"normal"}
{"timestamp":1748570749048,"host":"hivenode02","text":"systemd-logind: New session 2235021 of user root.","label":"normal"}
{"timestamp":1748570899151,"host":"hivenode02","text":"python: -------------- celery@hivenode02 v4.2.1 (windowlicker)","label":"normal"}
{"timestamp":1748570956805,"host":"hivenode02","text":"systemd: Started Session 2235148 of user root.","label":"normal"}
{"timestamp":1748571062401,"host":"hivenode02","text":"xinetd[4580]: START: mongo_status pid=598478 from=::ffff:10.108.196.204","label":"normal"}
{"timestamp":1748571551225,"host":"hivenode02","text":"infinity[8164]: an error occurred while requesting bindings <urlopen error [Errno 111] Connection refused>","label":"abnormal"}
{"timestamp":1748572025036,"host":"hivenode02","text":"systemd-logind: Removed session 2235821.","label":"normal"}
{"timestamp":1748572474129,"host":"hivenode02","text":"systemd-logind: New session 2236113 of user root.","label":"normal"}
{"timestamp":1748572709686,"host":"hivenode02","text":"systemd: infi-celery.service: main process exited, code=exited, status=1\/FAILURE","label":"normal"}
{"timestamp":1748575866926,"host":"hivenode02","text":"systemd: Started Session 2238251 of user root.","label":"normal"}
{"timestamp":1748576603023,"host":"hivenode02","text":"xinetd[4580]: START: mongo_status pid=3997695 from=::ffff:10.108.196.202","label":"normal"}
{"timestamp":1748576875958,"host":"hivenode02","text":"systemd-logind: New session 2238889 of user root.","label":"normal"}
{"timestamp":1748576965562,"host":"hivenode02","text":"systemd-logind: Removed session 2238946.","label":"normal"}
{"timestamp":1748577249848,"host":"hivenode02","text":"python: \/usr\/lib\/python2.7\/site-packages\/celery\/platforms.py:796: RuntimeWarning: You're running the worker with superuser privileges: this is","label":"normal"}
{"timestamp":1748578154870,"host":"hivenode02","text":"xinetd[4580]: EXIT: mysql_status status=0 pid=1960238 duration=0(sec)","label":"normal"}
{"timestamp":1748579705182,"host":"hivenode02","text":"infinity[8164]: an error occurred while requesting bindings <urlopen error [Errno 111] Connection refused>","label":"abnormal"}
{"timestamp":1748580486259,"host":"hivenode02","text":"systemd: Unit infi-celery.service entered failed state.","label":"normal"}
{"timestamp":1748581450906,"host":"hivenode02","text":"python: - ** ---------- .> results:     elasticsearch:\/\/10.0.100.105:8200\/infi_queue_result\/queue_result","label":"normal"}
{"timestamp":1748582087513,"host":"hivenode02","text":"python: absolutely not recommended!","label":"normal"}
{"timestamp":1748582886730,"host":"hivenode02","text":"xinetd[4580]: EXIT: mysql_status status=0 pid=26440 duration=0(sec)","label":"normal"}
{"timestamp":1748584285251,"host":"hivenode02","text":"systemd-logind: Removed session 2243600.","label":"normal"}
{"timestamp":1748584866937,"host":"hivenode02","text":"systemd: Starting Session 2243980 of user root.","label":"normal"}
{"timestamp":1748585017487,"host":"hivenode02","text":"systemd: Starting Session 2244075 of user root.","label":"normal"}
{"timestamp":1748585426485,"host":"hivenode02","text":"systemd: Started Session 2244344 of user root.","label":"normal"}
{"timestamp":1748586296007,"host":"hivenode02","text":"systemd: Starting Infinity Celery Worker Service...","label":"normal"}
{"timestamp":1748586376126,"host":"hivenode02","text":"python: absolutely not recommended!","label":"normal"}
{"timestamp":1748587071579,"host":"hivenode02","text":"systemd-logind: New session 2245381 of user root.","label":"normal"}
{"timestamp":1748587580923,"host":"hivenode02","text":"xinetd[4580]: START: zk_status pid=2311065 from=::ffff:10.108.196.204","label":"normal"}
{"timestamp":1748588563698,"host":"hivenode02","text":"python: - ** ---------- .> transport:   amqp:\/\/rabbitmq:**@10.0.100.105:5672\/\/","label":"normal"}
{"timestamp":1748589435824,"host":"hivenode02","text":"systemd: Started Infinity Celery Worker Service.","label":"normal"}
{"timestamp":1748590709653,"host":"hivenode02","text":"systemd: Started Session 2247658 of user root.","label":"normal"}
{"timestamp":1748590986004,"host":"hivenode02","text":"python: - ** ---------- .> results:     elasticsearch:\/\/10.0.100.105:8200\/infi_queue_result\/queue_result","label":"normal"}
{"timestamp":1748591703667,"host":"hivenode02","text":"python: .> infinity_queue   exchange=infinity_exchange(direct) key=infinity_queue","label":"normal"}
{"timestamp":1748591799309,"host":"hivenode02","text":"xinetd[4580]: EXIT: mysql_status status=0 pid=3900246 duration=1(sec)","label":"normal"}
{"timestamp":1748592493216,"host":"hivenode02","text":"python: - ** ---------- [config]","label":"normal"}
{"timestamp":1748593507641,"host":"hivenode02","text":"python: .> node2            exchange=node2(direct) key=node2","label":"normal"}
{"timestamp":1748593572811,"host":"hivenode02","text":"python: - ** ---------- [config]","label":"normal"}
{"timestamp":1748593931158,"host":"hivenode02","text":"infinity[642836]: an error occurred while requesting bindings <urlopen error [Errno 111] Connection refused>","label":"abnormal"}
{"timestamp":1748595584762,"host":"hivenode02","text":"systemd: infi-celery.service holdoff time over, scheduling restart.","label":"normal"}
{"timestamp":1748596944319,"host":"hivenode02","text":"infinity[642836]: an error occurred while requesting bindings <urlopen error [Errno 111] Connection refused>","label":"abnormal"}
{"timestamp":1748597602634,"host":"hivenode02","text":"systemd-logind: Removed session 2252126.","label":"normal"}
{"timestamp":1748598106671,"host":"hivenode02","text":"systemd: infi-celery.service: main process exited, code=exited, status=1\/FAILURE","label":"normal"}
{"timestamp":1748598658225,"host":"hivenode02","text":"xinetd[4580]: EXIT: mongo_status status=0 pid=876135 duration=0(sec)","label":"normal"}
{"timestamp":1748599482167,"host":"hivenode02","text":"python: -------------- celery@hivenode02 v4.2.1 (windowlicker)","label":"normal"}
{"timestamp":1748599496533,"host":"hivenode02","text":"python: -------------- [queues]","label":"normal"}
{"timestamp":1748600299825,"host":"hivenode02","text":"systemd: Started Infinity Celery Worker Service.","label":"normal"}
{"timestamp":1748600473505,"host":"hivenode02","text":"systemd: Starting Session 2253984 of user root.","label":"normal"}
{"timestamp":1748600817222,"host":"hivenode02","text":"systemd: Started Session 2254204 of user root.","label":"normal"}
{"timestamp":1748604014034,"host":"hivenode02","text":"systemd-logind: New session 2256272 of user root.","label":"normal"}
{"timestamp":1748604181226,"host":"hivenode02","text":"infinity[642836]: an error occurred while requesting bindings <urlopen error [Errno 111] Connection refused>","label":"abnormal"}
{"timestamp":1748604278713,"host":"hivenode02","text":"python: -------------- celery@hivenode02 v4.2.1 (windowlicker)","label":"normal"}
{"timestamp":1748604467168,"host":"hivenode02","text":"python: [tasks]","label":"normal"}
{"timestamp":1748604513373,"host":"hivenode02","text":"xinetd[4580]: START: mongo_status pid=650292 from=::ffff:10.108.196.205","label":"normal"}
{"timestamp":1748605299734,"host":"hivenode02","text":"systemd-logind: New session 2257099 of user root.","label":"normal"}
{"timestamp":1748605366456,"host":"hivenode02","text":"python: - ** ---------- [config]","label":"normal"}
{"timestamp":1748605688295,"host":"hivenode02","text":"infinity[642836]: an error occurred while requesting bindings <urlopen error [Errno 111] Connection refused>","label":"abnormal"}
{"timestamp":1748606193147,"host":"hivenode02","text":"python: .> infinity_queue   exchange=infinity_exchange(direct) key=infinity_queue","label":"normal"}
{"timestamp":1748607211755,"host":"hivenode02","text":"systemd: Started Session 2258332 of user root.","label":"normal"}
{"timestamp":1748607880141,"host":"hivenode02","text":"systemd: Starting Session 2258760 of user root.","label":"normal"}
{"timestamp":1748608576178,"host":"hivenode02","text":"xinetd[4580]: START: zk_status pid=2067043 from=::ffff:10.108.196.205","label":"normal"}
{"timestamp":1748609866676,"host":"hivenode02","text":"xinetd[4580]: START: zk_status pid=3869389 from=::ffff:10.108.196.201","label":"normal"}
{"timestamp":1748612008233,"host":"hivenode02","text":"xinetd[4580]: EXIT: mysql_status status=0 pid=2675085 duration=1(sec)","label":"normal"}
{"timestamp":1748612118816,"host":"hivenode02","text":"systemd: Starting Session 2261495 of user root.","label":"normal"}
{"timestamp":1748613320061,"host":"hivenode02","text":"systemd: Started Session 2262268 of user root.","label":"normal"}
{"timestamp":1748614239155,"host":"hivenode02","text":"xinetd[4580]: EXIT: zk_status status=0 pid=1570928 duration=0(sec)","label":"normal"}
{"timestamp":1748614870252,"host":"hivenode02","text":"systemd: Started Session 2263263 of user root.","label":"normal"}
{"timestamp":1748616551822,"host":"hivenode02","text":"systemd: infi-celery.service holdoff time over, scheduling restart.","label":"normal"}
{"timestamp":1748617147012,"host":"hivenode02","text":"infinity[642836]: an error occurred while requesting bindings <urlopen error [Errno 111] Connection refused>","label":"abnormal"}
{"timestamp":1748618646654,"host":"hivenode02","text":"python: .> node2            exchange=node2(direct) key=node2","label":"normal"}
{"timestamp":1748618820517,"host":"hivenode02","text":"python: -- * - **** ---","label":"normal"}
{"timestamp":1748618878350,"host":"hivenode02","text":"python: -- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)","label":"normal"}
{"timestamp":1748619122374,"host":"hivenode02","text":"systemd-logind: Removed session 2266013.","label":"normal"}
{"timestamp":1748619471759,"host":"hivenode02","text":"python: \/usr\/lib\/python2.7\/site-packages\/celery\/platforms.py:796: RuntimeWarning: You're running the worker with superuser privileges: this is","label":"normal"}
{"timestamp":1748622169395,"host":"hivenode02","text":"python: -------------- [queues]","label":"normal"}
{"timestamp":1748623193188,"host":"hivenode02","text":"xinetd[4580]: START: mysql_status pid=1455656 from=::ffff:10.108.196.201","label":"normal"}
{"timestamp":1748623278701,"host":"hivenode02","text":"systemd: Unit infi-celery.service entered failed state.","label":"normal"}
{"timestamp":1748623647173,"host":"hivenode02","text":"xinetd[4580]: START: mysql_status pid=2062994 from=::ffff:10.108.196.204","label":"normal"}
{"timestamp":1748624096903,"host":"hivenode02","text":"python: [tasks]","label":"normal"}
{"timestamp":1748624100188,"host":"hivenode02","text":"xinetd[4580]: START: mysql_status pid=2685089 from=::ffff:10.108.196.201","label":"normal"}
{"timestamp":1748624421732,"host":"hivenode02","text":"python: uid=uid, euid=euid, gid=gid, egid=egid,","label":"normal"}
{"timestamp":1748624892502,"host":"hivenode02","text":"python: uid=uid, euid=euid, gid=gid, egid=egid,","label":"normal"}
{"timestamp":1748625117697,"host":"hivenode02","text":"systemd: Started Session 2269893 of user root.","label":"normal"}
{"timestamp":1748626326238,"host":"hivenode02","text":"python: absolutely not recommended!","label":"normal"}
{"timestamp":1748627595133,"host":"hivenode02","text":"systemd-logind: New session 2271495 of user root.","label":"normal"}
{"timestamp":1748627874572,"host":"hivenode02","text":"systemd: infi-celery.service holdoff time over, scheduling restart.","label":"normal"}
{"timestamp":1748629572373,"host":"hivenode02","text":"bash: WARNING: 2025\/05\/31 02:26:12 grpc: Server.Serve failed to create ServerTransport:  connection error: desc = \"transport: http2Server.HandleStreams failed to read initial settings frame: read tcp 10.0.100.102:2379->10.0.100.106:39930: read: connection reset by peer\"","label":"abnormal"}
{"timestamp":1748629889718,"host":"hivenode02","text":"python: absolutely not recommended!","label":"normal"}
{"timestamp":1748629912703,"host":"hivenode02","text":"python: - ** ---------- [config]","label":"normal"}
{"timestamp":1748630709882,"host":"hivenode02","text":"python: --- * ***  * -- Linux-3.10.0-1160.el7.x86_64-x86_64-with-centos-7.4.1708-Core 2025-05-31 02:45:08","label":"normal"}
{"timestamp":1748631303742,"host":"hivenode02","text":"python: --- * ***  * -- Linux-3.10.0-1160.el7.x86_64-x86_64-with-centos-7.4.1708-Core 2025-05-31 02:55:02","label":"normal"}
{"timestamp":1748631868914,"host":"hivenode02","text":"python: - *** --- * --- .> concurrency: 4 (prefork)","label":"normal"}
{"timestamp":1748633505590,"host":"hivenode02","text":"python: uid=uid, euid=euid, gid=gid, egid=egid,","label":"normal"}
{"timestamp":1748633797787,"host":"hivenode02","text":"systemd: Unit infi-celery.service entered failed state.","label":"normal"}
{"timestamp":1748634935899,"host":"hivenode02","text":"python: - ** ---------- .> results:     elasticsearch:\/\/10.0.100.105:8200\/infi_queue_result\/queue_result","label":"normal"}
{"timestamp":1748636662578,"host":"hivenode02","text":"xinetd[4580]: START: mysql_status pid=3292539 from=::ffff:10.108.196.201","label":"normal"}
{"timestamp":1748637407141,"host":"hivenode02","text":"named[7310]: error (network unreachable) resolving '.\/A\/IN': 2001:500:a8::e#53","label":"abnormal"}
{"timestamp":1748637424746,"host":"hivenode02","text":"named[7310]: error (network unreachable) resolving 'osce12-p.activeupdate.asiainfo-sec.com\/A\/IN': 2001:500:2f::f#53","label":"abnormal"}
{"timestamp":1748637464318,"host":"hivenode02","text":"named[7310]: error (network unreachable) resolving 'ssl.gstatic.com\/A\/IN': 2001:500:2f::f#53","label":"abnormal"}
{"timestamp":1748637469919,"host":"hivenode02","text":"named[7310]: error (network unreachable) resolving 'ssl.gstatic.com\/A\/IN': 2001:500:2d::d#53","label":"abnormal"}
{"timestamp":1748637494132,"host":"hivenode02","text":"named[7310]: error (network unreachable) resolving 'win8.ipv6.microsoft.com\/A\/IN': 2001:500:1::53#53","label":"abnormal"}
{"timestamp":1748637526329,"host":"hivenode02","text":"named[7310]: error (network unreachable) resolving 'www.baidu.com\/A\/IN': 2001:500:2f::f#53","label":"abnormal"}
{"timestamp":1748637530012,"host":"hivenode02","text":"named[7310]: error (network unreachable) resolving 'win8.ipv6.microsoft.com\/A\/IN': 2001:500:12::d0d#53","label":"abnormal"}
{"timestamp":1748637619875,"host":"hivenode02","text":"named[7310]: error (network unreachable) resolving 'win8.ipv6.microsoft.com\/A\/IN': 2001:500:a8::e#53","label":"abnormal"}
{"timestamp":1748637622476,"host":"hivenode02","text":"named[7310]: error (network unreachable) resolving '.\/NS\/IN': 2001:503:c27::2:30#53","label":"abnormal"}
{"timestamp":1748637658573,"host":"hivenode02","text":"named[7310]: error (network unreachable) resolving '.\/AAAA\/IN': 2001:500:9f::42#53","label":"abnormal"}
{"timestamp":1748637696895,"host":"hivenode02","text":"named[7310]: error (network unreachable) resolving 'win8.ipv6.microsoft.com\/A\/IN': 2001:500:2f::f#53","label":"abnormal"}
{"timestamp":1748637743574,"host":"hivenode02","text":"named[7310]: error (network unreachable) resolving 'ct.duba.net\/A\/IN': 2001:500:12::d0d#53","label":"abnormal"}
{"timestamp":1748637839550,"host":"hivenode02","text":"named[7310]: error (network unreachable) resolving 'win8.ipv6.microsoft.com\/A\/IN': 2001:503:c27::2:30#53","label":"abnormal"}
{"timestamp":1748637897130,"host":"hivenode02","text":"named[7310]: error (network unreachable) resolving '.\/A\/IN': 2001:500:2d::d#53","label":"abnormal"}
{"timestamp":1748637967335,"host":"hivenode02","text":"named[7310]: error (network unreachable) resolving 'win8.ipv6.microsoft.com\/A\/IN': 2001:500:2::c#53","label":"abnormal"}
{"timestamp":1748638017677,"host":"hivenode02","text":"named[7310]: error (network unreachable) resolving 'www.baidu.com\/A\/IN': 2001:500:84::b#53","label":"abnormal"}
{"timestamp":1748638082166,"host":"hivenode02","text":"named[7310]: error (network unreachable) resolving 'sn.splashtop.com\/A\/IN': 2001:503:ba3e::2:30#53","label":"abnormal"}
{"timestamp":1748638083894,"host":"hivenode02","text":"systemd: Unit infi-celery.service entered failed state.","label":"normal"}
{"timestamp":1748638093021,"host":"hivenode02","text":"named[7310]: error (network unreachable) resolving '.\/A\/IN': 2001:500:2::c#53","label":"abnormal"}
{"timestamp":1748638153382,"host":"hivenode02","text":"named[7310]: error (network unreachable) resolving 'sn.splashtop.com\/A\/IN': 2001:500:84::b#53","label":"abnormal"}
{"timestamp":1748638288919,"host":"hivenode02","text":"named[7310]: error (network unreachable) resolving '.\/A\/IN': 2001:500:9f::42#53","label":"abnormal"}
{"timestamp":1748639179622,"host":"hivenode02","text":"named[7310]: error (network unreachable) resolving 'qing.wps.cn\/A\/IN': 2001:503:c27::2:30#53","label":"abnormal"}
{"timestamp":1748639386693,"host":"hivenode02","text":"named[7310]: error (network unreachable) resolving 'win8.ipv6.microsoft.com\/A\/IN': 2001:500:2f::f#53","label":"abnormal"}
{"timestamp":1748639639820,"host":"hivenode02","text":"named[7310]: error (network unreachable) resolving 'clientservices.googleapis.com\/A\/IN': 2001:500:12::d0d#53","label":"abnormal"}
{"timestamp":1748639762304,"host":"hivenode02","text":"named[7310]: error (network unreachable) resolving 'drive.wps.cn\/A\/IN': 2001:500:12::d0d#53","label":"abnormal"}
{"timestamp":1748639841477,"host":"hivenode02","text":"infinity[1900933]: an error occurred while requesting bindings <urlopen error [Errno 111] Connection refused>","label":"abnormal"}
{"timestamp":1748640380317,"host":"hivenode02","text":"named[7310]: error (network unreachable) resolving 'win8.ipv6.microsoft.com\/A\/IN': 2001:500:12::d0d#53","label":"abnormal"}
{"timestamp":1748641780959,"host":"hivenode02","text":"python: absolutely not recommended!","label":"normal"}
{"timestamp":1748642587342,"host":"hivenode02","text":"systemd: Started Session 2281103 of user root.","label":"normal"}
{"timestamp":1748643768465,"host":"hivenode02","text":"infinity[1900933]: an error occurred while requesting bindings <urlopen error [Errno 111] Connection refused>","label":"abnormal"}
{"timestamp":1748644870146,"host":"hivenode02","text":"systemd-logind: New session 2282549 of user root.","label":"normal"}
{"timestamp":1748646891028,"host":"hivenode02","text":"systemd-logind: New session 2283834 of user root.","label":"normal"}
{"timestamp":1748648499244,"host":"hivenode02","text":"systemd: Starting Infinity Celery Worker Service...","label":"normal"}
{"timestamp":1748649305398,"host":"hivenode02","text":"systemd-logind: Removed session 2285386.","label":"normal"}
{"timestamp":1748651372401,"host":"hivenode02","text":"systemd-logind: New session 2286697 of user root.","label":"normal"}
{"timestamp":1748651993961,"host":"hivenode02","text":"xinetd[4580]: EXIT: zk_status status=0 pid=3448646 duration=0(sec)","label":"normal"}
{"timestamp":1748652285596,"host":"hivenode02","text":"xinetd[4580]: EXIT: zk_status status=0 pid=3844751 duration=0(sec)","label":"normal"}
{"timestamp":1748653420154,"host":"hivenode02","text":"xinetd[4580]: EXIT: mysql_status status=0 pid=1208502 duration=1(sec)","label":"normal"}
{"timestamp":1748653946096,"host":"hivenode02","text":"xinetd[4580]: START: mysql_status pid=1953052 from=::ffff:10.108.196.201","label":"normal"}
{"timestamp":1748654199816,"host":"hivenode02","text":"xinetd[4580]: EXIT: mongo_status status=0 pid=2293319 duration=0(sec)","label":"normal"}
{"timestamp":1748655016900,"host":"hivenode02","text":"systemd: infi-celery.service holdoff time over, scheduling restart.","label":"normal"}
{"timestamp":1748655924291,"host":"hivenode02","text":"xinetd[4580]: START: zk_status pid=475094 from=::ffff:10.108.196.201","label":"normal"}
{"timestamp":1748656187777,"host":"hivenode02","text":"systemd: Starting Session 2289756 of user root.","label":"normal"}
{"timestamp":1748656914757,"host":"hivenode02","text":"python: uid=uid, euid=euid, gid=gid, egid=egid,","label":"normal"}
{"timestamp":1748657039727,"host":"hivenode02","text":"systemd: Unit infi-celery.service entered failed state.","label":"normal"}
{"timestamp":1748657662763,"host":"hivenode02","text":"infinity[1900933]: an error occurred while requesting bindings <urlopen error [Errno 111] Connection refused>","label":"abnormal"}
{"timestamp":1748657763293,"host":"hivenode02","text":"systemd: Started Session 2290772 of user root.","label":"normal"}
{"timestamp":1748658110106,"host":"hivenode02","text":"python: - ** ---------- .> transport:   amqp:\/\/rabbitmq:**@10.0.100.105:5672\/\/","label":"normal"}
{"timestamp":1748658110108,"host":"hivenode02","text":"python: .> infinity_queue   exchange=infinity_exchange(direct) key=infinity_queue","label":"normal"}
{"timestamp":1748658266115,"host":"hivenode02","text":"infinity[1900933]: an error occurred while requesting bindings <urlopen error [Errno 111] Connection refused>","label":"abnormal"}
{"timestamp":1748658699449,"host":"hivenode02","text":"xinetd[4580]: EXIT: mysql_status status=0 pid=110993 duration=1(sec)","label":"normal"}
{"timestamp":1748659348886,"host":"hivenode02","text":"xinetd[4580]: START: mysql_status pid=985117 from=::ffff:10.108.196.205","label":"normal"}
{"timestamp":1748660854795,"host":"hivenode02","text":"xinetd[4580]: EXIT: zk_status status=0 pid=3073143 duration=0(sec)","label":"normal"}
{"timestamp":1748661202194,"host":"hivenode02","text":"xinetd[4580]: START: mysql_status pid=3529012 from=::ffff:10.108.196.204","label":"normal"}
{"timestamp":1748661909962,"host":"hivenode02","text":"xinetd[4580]: EXIT: mysql_status status=0 pid=306414 duration=0(sec)","label":"normal"}
{"timestamp":1748662535593,"host":"hivenode02","text":"systemd-logind: Removed session 2293791.","label":"normal"}
{"timestamp":1748662881853,"host":"hivenode02","text":"systemd: Started Session 2294017 of user root.","label":"normal"}
{"timestamp":1748663052484,"host":"hivenode02","text":"systemd: Started Infinity Celery Worker Service.","label":"normal"}
{"timestamp":1748663226229,"host":"hivenode02","text":"systemd: Started Infinity Celery Worker Service.","label":"normal"}
{"timestamp":1748665235988,"host":"hivenode02","text":"systemd: infi-celery.service failed.","label":"normal"}
{"timestamp":1748665823403,"host":"hivenode02","text":"systemd: Started Session 2295899 of user root.","label":"normal"}
{"timestamp":1748666229700,"host":"hivenode02","text":"python: ---- **** -----","label":"normal"}
{"timestamp":1748666696719,"host":"hivenode02","text":"systemd-logind: New session 2296441 of user root.","label":"normal"}
{"timestamp":1748667604475,"host":"hivenode02","text":"python: absolutely not recommended!","label":"normal"}
{"timestamp":1748667854054,"host":"hivenode02","text":"systemd: Started Session 2297180 of user root.","label":"normal"}
{"timestamp":1748668213642,"host":"hivenode02","text":"python: -------------- celery@hivenode02 v4.2.1 (windowlicker)","label":"normal"}
{"timestamp":1748668804910,"host":"hivenode02","text":"python: - ** ---------- [config]","label":"normal"}
{"timestamp":1748668804911,"host":"hivenode02","text":"python: - ** ---------- .> results:     elasticsearch:\/\/10.0.100.105:8200\/infi_queue_result\/queue_result","label":"normal"}
{"timestamp":1748668818240,"host":"hivenode02","text":"python: uid=uid, euid=euid, gid=gid, egid=egid,","label":"normal"}
{"timestamp":1748668835246,"host":"hivenode02","text":"infinity[1900933]: an error occurred while requesting bindings <urlopen error [Errno 111] Connection refused>","label":"abnormal"}
{"timestamp":1748669019253,"host":"hivenode02","text":"systemd: Starting Session 2297913 of user root.","label":"normal"}
{"timestamp":1748669689969,"host":"hivenode02","text":"python: uid=uid, euid=euid, gid=gid, egid=egid,","label":"normal"}
{"timestamp":1748670601200,"host":"hivenode02","text":"systemd: Started Session 2298933 of user root.","label":"normal"}
{"timestamp":1748670645256,"host":"hivenode02","text":"infinity[1900933]: an error occurred while requesting bindings <urlopen error [Errno 111] Connection refused>","label":"abnormal"}
{"timestamp":1748671057606,"host":"hivenode02","text":"xinetd[4580]: EXIT: mongo_status status=0 pid=372288 duration=0(sec)","label":"normal"}
{"timestamp":1748671364629,"host":"hivenode02","text":"python: - ** ---------- .> results:     elasticsearch:\/\/10.0.100.105:8200\/infi_queue_result\/queue_result","label":"normal"}
{"timestamp":1748671407875,"host":"hivenode02","text":"python: . infinity.task.tasks.infi_cluster","label":"normal"}
{"timestamp":1748673975521,"host":"hivenode02","text":"systemd: Started Session 2301101 of user root.","label":"normal"}
{"timestamp":1748674787961,"host":"hivenode02","text":"python: - ** ---------- .> results:     elasticsearch:\/\/10.0.100.105:8200\/infi_queue_result\/queue_result","label":"normal"}
{"timestamp":1748676372553,"host":"hivenode02","text":"xinetd[4580]: START: mysql_status pid=3488599 from=::ffff:10.108.196.204","label":"normal"}
{"timestamp":1748677175014,"host":"hivenode02","text":"python: \/usr\/lib\/python2.7\/site-packages\/celery\/platforms.py:796: RuntimeWarning: You're running the worker with superuser privileges: this is","label":"normal"}
{"timestamp":1748677472386,"host":"hivenode02","text":"python: -------------- [queues]","label":"normal"}
{"timestamp":1748677537345,"host":"hivenode02","text":"python: .> node2            exchange=node2(direct) key=node2","label":"normal"}
{"timestamp":1748677834879,"host":"hivenode02","text":"kill: kill: cannot find process \"\"","label":"normal"}
{"timestamp":1748678262711,"host":"hivenode02","text":"xinetd[4580]: START: mysql_status pid=1926763 from=::ffff:10.108.196.201","label":"normal"}
{"timestamp":1748678529890,"host":"hivenode02","text":"kill: kill: cannot find process \"\"","label":"normal"}
{"timestamp":1748679007566,"host":"hivenode02","text":"python: . infinity.task.tasks.infi_cluster","label":"normal"}
{"timestamp":1748679333400,"host":"hivenode02","text":"xinetd[4580]: START: mysql_status pid=3417862 from=::ffff:10.108.196.205","label":"normal"}
{"timestamp":1748680320611,"host":"hivenode02","text":"xinetd[4580]: EXIT: mysql_status status=0 pid=603287 duration=0(sec)","label":"normal"}
{"timestamp":1748680838693,"host":"hivenode02","text":"xinetd[4580]: START: mysql_status pid=1345684 from=::ffff:10.108.196.201","label":"normal"}
{"timestamp":1748682061204,"host":"hivenode02","text":"python: \/usr\/lib\/python2.7\/site-packages\/celery\/platforms.py:796: RuntimeWarning: You're running the worker with superuser privileges: this is","label":"normal"}
{"timestamp":1748682130619,"host":"hivenode02","text":"infinity[2726725]: an error occurred while requesting bindings <urlopen error [Errno 111] Connection refused>","label":"abnormal"}
{"timestamp":1748682402578,"host":"hivenode02","text":"systemd: Started Session 2306534 of user root.","label":"normal"}
{"timestamp":1748682733261,"host":"hivenode02","text":"infinity[2726725]: an error occurred while requesting bindings <urlopen error [Errno 111] Connection refused>","label":"abnormal"}
{"timestamp":1748683154509,"host":"hivenode02","text":"systemd: Started Session 2307024 of user root.","label":"normal"}
{"timestamp":1748683843892,"host":"hivenode02","text":"python: [tasks]","label":"normal"}
{"timestamp":1748685111383,"host":"hivenode02","text":"xinetd[4580]: START: zk_status pid=3106774 from=::ffff:10.108.196.202","label":"normal"}
{"timestamp":1748685445755,"host":"hivenode02","text":"infinity[2726725]: an error occurred while requesting bindings <urlopen error [Errno 111] Connection refused>","label":"abnormal"}
{"timestamp":1748687754698,"host":"hivenode02","text":"systemd: infi-celery.service: main process exited, code=exited, status=1\/FAILURE","label":"normal"}
{"timestamp":1748687774615,"host":"hivenode02","text":"systemd-logind: Removed session 2310012.","label":"normal"}
{"timestamp":1748687926276,"host":"hivenode02","text":"systemd: infi-celery.service holdoff time over, scheduling restart.","label":"normal"}
{"timestamp":1748689226836,"host":"hivenode02","text":"systemd-logind: Removed session 2310958.","label":"normal"}
{"timestamp":1748690419591,"host":"hivenode02","text":"systemd: Started Session 2311731 of user root.","label":"normal"}
{"timestamp":1748692557933,"host":"hivenode02","text":"python: - ** ---------- .> app:         __main__:0x1852a90","label":"normal"}
{"timestamp":1748693130287,"host":"hivenode02","text":"python: - ** ---------- .> transport:   amqp:\/\/rabbitmq:**@10.0.100.105:5672\/\/","label":"normal"}
{"timestamp":1748693150718,"host":"hivenode02","text":"python: User information: uid=0 euid=0 gid=0 egid=0","label":"normal"}
{"timestamp":1748693369263,"host":"hivenode02","text":"python: - ** ---------- .> app:         __main__:0x141fa90","label":"normal"}
{"timestamp":1748693695099,"host":"hivenode02","text":"python: [tasks]","label":"normal"}
{"timestamp":1748694381968,"host":"hivenode02","text":"systemd-logind: New session 2314288 of user root.","label":"normal"}
{"timestamp":1748694672749,"host":"hivenode02","text":"python: Please specify a different user using the --uid option.","label":"normal"}
{"timestamp":1748695252485,"host":"hivenode02","text":"python: absolutely not recommended!","label":"normal"}
{"timestamp":1748696226470,"host":"hivenode02","text":"xinetd[4580]: START: mysql_status pid=1884379 from=::ffff:10.108.196.202","label":"normal"}
{"timestamp":1748696589414,"host":"hivenode02","text":"infinity[2726725]: monitor net list is null","label":"normal"}
{"timestamp":1748697214960,"host":"hivenode02","text":"infinity[2726725]: an error occurred while requesting bindings <urlopen error [Errno 111] Connection refused>","label":"abnormal"}
{"timestamp":1748697363824,"host":"hivenode02","text":"systemd: Started Infinity Celery Worker Service.","label":"normal"}
{"timestamp":1748697971301,"host":"hivenode02","text":"xinetd[4580]: START: mongo_status pid=94589 from=::ffff:10.108.196.201","label":"normal"}
{"timestamp":1748698808970,"host":"hivenode02","text":"python: --- ***** -----","label":"normal"}
{"timestamp":1748698962168,"host":"hivenode02","text":"xinetd[4580]: EXIT: mysql_status status=0 pid=1461149 duration=1(sec)","label":"normal"}
{"timestamp":1748699627625,"host":"hivenode02","text":"infinity[2726725]: an error occurred while requesting bindings <urlopen error [Errno 111] Connection refused>","label":"abnormal"}
{"timestamp":1748700004648,"host":"hivenode02","text":"python: - ** ---------- .> transport:   amqp:\/\/rabbitmq:**@10.0.100.105:5672\/\/","label":"normal"}
{"timestamp":1748700432120,"host":"hivenode02","text":"systemd: infi-celery.service: main process exited, code=exited, status=1\/FAILURE","label":"normal"}
{"timestamp":1748701186334,"host":"hivenode02","text":"bash: WARNING: 2025\/05\/31 22:19:46 grpc: Server.Serve failed to create ServerTransport:  connection error: desc = \"transport: http2Server.HandleStreams failed to read initial settings frame: read tcp 10.0.100.102:2379->10.0.100.106:33710: read: connection reset by peer\"","label":"abnormal"}
{"timestamp":1748701392449,"host":"hivenode02","text":"systemd: Started Session 2318771 of user root.","label":"normal"}
{"timestamp":1748702893822,"host":"hivenode02","text":"python: --- * ***  * -- Linux-3.10.0-1160.el7.x86_64-x86_64-with-centos-7.4.1708-Core 2025-05-31 22:48:12","label":"normal"}
{"timestamp":1748703236352,"host":"hivenode02","text":"xinetd[4580]: EXIT: zk_status status=0 pid=3242419 duration=0(sec)","label":"normal"}
{"timestamp":1748704385896,"host":"hivenode02","text":"python: .> node2            exchange=node2(direct) key=node2","label":"normal"}
{"timestamp":1748705413834,"host":"hivenode02","text":"python: --- ***** -----","label":"normal"}
{"timestamp":1748706194889,"host":"hivenode02","text":"xinetd[4580]: START: mongo_status pid=3190105 from=::ffff:10.108.196.204","label":"normal"}
{"timestamp":1748708136597,"host":"hivenode02","text":"python: Please specify a different user using the --uid option.","label":"normal"}
{"timestamp":1748708471933,"host":"hivenode02","text":"systemd-logind: Removed session 2323352.","label":"normal"}
{"timestamp":1748709280384,"host":"hivenode02","text":"xinetd[4580]: START: zk_status pid=3295853 from=::ffff:10.108.196.201","label":"normal"}
{"timestamp":1748709408733,"host":"hivenode02","text":"xinetd[4580]: EXIT: mysql_status status=0 pid=3469273 duration=0(sec)","label":"normal"}
{"timestamp":1748709716662,"host":"hivenode02","text":"kill: kill: cannot find process \"\"","label":"normal"}
{"timestamp":1748709800422,"host":"hivenode02","text":"systemd: Starting Session 2324211 of user root.","label":"normal"}
{"timestamp":1748710182454,"host":"hivenode02","text":"infinity[2726725]: an error occurred while requesting bindings <urlopen error [Errno 111] Connection refused>","label":"abnormal"}
{"timestamp":1748711512786,"host":"hivenode02","text":"systemd: infi-celery.service: control process exited, code=exited status=1","label":"normal"}
{"timestamp":1748711679472,"host":"hivenode02","text":"xinetd[4580]: EXIT: mysql_status status=0 pid=2416844 duration=1(sec)","label":"normal"}
{"timestamp":1748713706825,"host":"hivenode02","text":"systemd: Starting Infinity Celery Worker Service...","label":"normal"}
{"timestamp":1748714023135,"host":"hivenode02","text":"systemd: Started Session 2326957 of user root.","label":"normal"}
{"timestamp":1748715007278,"host":"hivenode02","text":"named[7310]: error (network unreachable) resolving 'update.googleapis.com\/A\/IN': 2001:500:2f::f#53","label":"abnormal"}
{"timestamp":1748715013571,"host":"hivenode02","text":"named[7310]: error (network unreachable) resolving 'win8.ipv6.microsoft.com\/A\/IN': 2001:500:2::c#53","label":"abnormal"}
{"timestamp":1748715017574,"host":"hivenode02","text":"named[7310]: error (network unreachable) resolving 'win8.ipv6.microsoft.com\/A\/IN': 2001:7fe::53#53","label":"abnormal"}
{"timestamp":1748715036653,"host":"hivenode02","text":"named[7310]: error (network unreachable) resolving '.\/NS\/IN': 2001:500:1::53#53","label":"abnormal"}
{"timestamp":1748715056413,"host":"hivenode02","text":"named[7310]: error (network unreachable) resolving '.\/AAAA\/IN': 2001:7fd::1#53","label":"abnormal"}
{"timestamp":1748715063231,"host":"hivenode02","text":"named[7310]: error (network unreachable) resolving '.\/AAAA\/IN': 2001:500:2d::d#53","label":"abnormal"}
{"timestamp":1748715079979,"host":"hivenode02","text":"named[7310]: error (network unreachable) resolving 'qing.wps.cn\/A\/IN': 2001:500:2::c#53","label":"abnormal"}
{"timestamp":1748715085747,"host":"hivenode02","text":"named[7310]: error (network unreachable) resolving 'clients5.google.com\/A\/IN': 2001:500:a8::e#53","label":"abnormal"}
{"timestamp":1748715180408,"host":"hivenode02","text":"named[7310]: error (network unreachable) resolving 'win8.ipv6.microsoft.com\/A\/IN': 2001:503:c27::2:30#53","label":"abnormal"}
{"timestamp":1748715180935,"host":"hivenode02","text":"named[7310]: error (network unreachable) resolving 'clients1.google.com\/A\/IN': 2001:7fe::53#53","label":"abnormal"}
{"timestamp":1748715190424,"host":"hivenode02","text":"named[7310]: error (network unreachable) resolving '.\/NS\/IN': 2001:500:84::b#53","label":"abnormal"}
{"timestamp":1748715213051,"host":"hivenode02","text":"named[7310]: error (network unreachable) resolving 'qing.wps.cn\/A\/IN': 2001:7fe::53#53","label":"abnormal"}
{"timestamp":1748715259377,"host":"hivenode02","text":"named[7310]: error (network unreachable) resolving 'ssl.gstatic.com\/A\/IN': 2001:500:12::d0d#53","label":"abnormal"}
{"timestamp":1748715293173,"host":"hivenode02","text":"named[7310]: error (network unreachable) resolving '.\/AAAA\/IN': 2001:7fe::53#53","label":"abnormal"}
{"timestamp":1748715349028,"host":"hivenode02","text":"named[7310]: error (network unreachable) resolving 'win8.ipv6.microsoft.com\/A\/IN': 2001:500:a8::e#53","label":"abnormal"}
{"timestamp":1748715555072,"host":"hivenode02","text":"named[7310]: error (network unreachable) resolving 'qing.wps.cn\/A\/IN': 2001:500:12::d0d#53","label":"abnormal"}
{"timestamp":1748715726530,"host":"hivenode02","text":"named[7310]: error (network unreachable) resolving '.\/NS\/IN': 2001:500:2f::f#53","label":"abnormal"}
{"timestamp":1748715744751,"host":"hivenode02","text":"named[7310]: error (network unreachable) resolving 'update.googleapis.com\/A\/IN': 2001:500:1::53#53","label":"abnormal"}
{"timestamp":1748715809126,"host":"hivenode02","text":"named[7310]: error (network unreachable) resolving 'update.googleapis.com\/A\/IN': 2001:500:12::d0d#53","label":"abnormal"}
{"timestamp":1748716198390,"host":"hivenode02","text":"named[7310]: error (network unreachable) resolving 'win8.ipv6.microsoft.com\/A\/IN': 2001:500:2::c#53","label":"abnormal"}
{"timestamp":1748716216176,"host":"hivenode02","text":"named[7310]: error (network unreachable) resolving 'www.qq.com\/A\/IN': 2001:7fd::1#53","label":"abnormal"}
{"timestamp":1748716331184,"host":"hivenode02","text":"named[7310]: error (network unreachable) resolving 'sls.update.microsoft.com\/A\/IN': 2001:500:12::d0d#53","label":"abnormal"}
{"timestamp":1748716887702,"host":"hivenode02","text":"named[7310]: error (network unreachable) resolving 'sn.splashtop.com\/A\/IN': 2001:500:84::b#53","label":"abnormal"}
{"timestamp":1748717097327,"host":"hivenode02","text":"named[7310]: error (network unreachable) resolving '.\/A\/IN': 2001:500:1::53#53","label":"abnormal"}
{"timestamp":1748717699238,"host":"hivenode02","text":"named[7310]: error (network unreachable) resolving '.\/A\/IN': 2001:7fd::1#53","label":"abnormal"}
{"timestamp":1748717838470,"host":"hivenode02","text":"named[7310]: error (network unreachable) resolving '.\/NS\/IN': 2001:503:c27::2:30#53","label":"abnormal"}
{"timestamp":1748717981501,"host":"hivenode02","text":"systemd: Starting Infinity Celery Worker Service...","label":"normal"}
{"timestamp":1748718068204,"host":"hivenode02","text":"named[7310]: error (network unreachable) resolving 'win8.ipv6.microsoft.com\/A\/IN': 2001:500:2::c#53","label":"abnormal"}
{"timestamp":1748719273974,"host":"hivenode02","text":"python: User information: uid=0 euid=0 gid=0 egid=0","label":"normal"}
{"timestamp":1748720893533,"host":"hivenode02","text":"systemd-logind: New session 2331374 of user root.","label":"normal"}
{"timestamp":1748721107636,"host":"hivenode02","text":"infinity[4139103]: an error occurred while requesting bindings <urlopen error [Errno 111] Connection refused>","label":"abnormal"}
{"timestamp":1748721310911,"host":"hivenode02","text":"python: .> node2            exchange=node2(direct) key=node2","label":"normal"}
{"timestamp":1748722711792,"host":"hivenode02","text":"xinetd[4580]: START: zk_status pid=871179 from=::ffff:10.108.196.201","label":"normal"}
{"timestamp":1748723019606,"host":"hivenode02","text":"systemd-logind: Removed session 2332733.","label":"normal"}
{"timestamp":1748724317406,"host":"hivenode02","text":"xinetd[4580]: EXIT: zk_status status=0 pid=3087081 duration=0(sec)","label":"normal"}
{"timestamp":1748726713824,"host":"hivenode02","text":"systemd: Starting Infinity Celery Worker Service...","label":"normal"}
{"timestamp":1748729257597,"host":"hivenode02","text":"infinity[4139103]: an error occurred while requesting bindings <urlopen error [Errno 111] Connection refused>","label":"abnormal"}
{"timestamp":1748730637057,"host":"hivenode02","text":"systemd-logind: Removed session 2337594.","label":"normal"}
{"timestamp":1748731263986,"host":"hivenode02","text":"python: absolutely not recommended!","label":"normal"}
{"timestamp":1748731669170,"host":"hivenode02","text":"infinity[4139103]: an error occurred while requesting bindings <urlopen error [Errno 111] Connection refused>","label":"abnormal"}
{"timestamp":1748732626506,"host":"hivenode02","text":"systemd: infi-celery.service holdoff time over, scheduling restart.","label":"normal"}
{"timestamp":1748735709720,"host":"hivenode02","text":"systemd: Started Session 2340824 of user root.","label":"normal"}
{"timestamp":1748736005153,"host":"hivenode02","text":"systemd: Started Session 2341018 of user root.","label":"normal"}
{"timestamp":1748736211662,"host":"hivenode02","text":"python: - *** --- * --- .> concurrency: 4 (prefork)","label":"normal"}
{"timestamp":1748736332404,"host":"hivenode02","text":"systemd-logind: Removed session 2341229.","label":"normal"}
{"timestamp":1748737036652,"host":"hivenode02","text":"python: -- * - **** ---","label":"normal"}
{"timestamp":1748737095314,"host":"hivenode02","text":"systemd: Starting Infinity Celery Worker Service...","label":"normal"}
{"timestamp":1748737330313,"host":"hivenode02","text":"python: - ** ---------- [config]","label":"normal"}
{"timestamp":1748739452046,"host":"hivenode02","text":"systemd-logind: Removed session 2343205.","label":"normal"}
{"timestamp":1748740462745,"host":"hivenode02","text":"python: - ** ---------- [config]","label":"normal"}
{"timestamp":1748741145568,"host":"hivenode02","text":"xinetd[4580]: START: mysql_status pid=1095367 from=::ffff:10.108.196.203","label":"normal"}
{"timestamp":1748741185052,"host":"hivenode02","text":"systemd-logind: Removed session 2344306.","label":"normal"}
{"timestamp":1748741966763,"host":"hivenode02","text":"systemd: infi-celery.service: control process exited, code=exited status=1","label":"normal"}
{"timestamp":1748743206618,"host":"hivenode02","text":"systemd: Starting Session 2345605 of user root.","label":"normal"}
{"timestamp":1748743389077,"host":"hivenode02","text":"systemd-logind: Removed session 2345722.","label":"normal"}
{"timestamp":1748744709202,"host":"hivenode02","text":"xinetd[4580]: START: mysql_status pid=1836442 from=::ffff:10.108.196.205","label":"normal"}
{"timestamp":1748747435335,"host":"hivenode02","text":"xinetd[4580]: EXIT: mongo_status status=0 pid=1370694 duration=0(sec)","label":"normal"}
{"timestamp":1748747880306,"host":"hivenode02","text":"python: -- * - **** ---","label":"normal"}
{"timestamp":1748749407203,"host":"hivenode02","text":"xinetd[4580]: EXIT: mysql_status status=0 pid=4059742 duration=1(sec)","label":"normal"}
{"timestamp":1748750151723,"host":"hivenode02","text":"systemd: Started Session 2350021 of user root.","label":"normal"}
{"timestamp":1748750167775,"host":"hivenode02","text":"systemd: Starting Session 2350033 of user root.","label":"normal"}
{"timestamp":1748750635794,"host":"hivenode02","text":"xinetd[4580]: EXIT: zk_status status=0 pid=1603866 duration=0(sec)","label":"normal"}
{"timestamp":1748751661918,"host":"hivenode02","text":"python: - ** ---------- .> transport:   amqp:\/\/rabbitmq:**@10.0.100.105:5672\/\/","label":"normal"}
{"timestamp":1748752373353,"host":"hivenode02","text":"xinetd[4580]: EXIT: mysql_status status=0 pid=3975413 duration=1(sec)","label":"normal"}
{"timestamp":1748752518400,"host":"hivenode02","text":"xinetd[4580]: EXIT: zk_status status=0 pid=4170442 duration=0(sec)","label":"normal"}
{"timestamp":1748752633439,"host":"hivenode02","text":"systemd: Started Session 2351607 of user root.","label":"normal"}
{"timestamp":1748752705290,"host":"hivenode02","text":"kill: kill: cannot find process \"\"","label":"normal"}
{"timestamp":1748754078315,"host":"hivenode02","text":"python: --- * ***  * -- Linux-3.10.0-1160.el7.x86_64-x86_64-with-centos-7.4.1708-Core 2025-06-01 13:01:17","label":"normal"}
{"timestamp":1748754236068,"host":"hivenode02","text":"systemd: Started Session 2352619 of user root.","label":"normal"}
{"timestamp":1748754649201,"host":"hivenode02","text":"systemd: Starting Session 2352889 of user root.","label":"normal"}
{"timestamp":1748756261330,"host":"hivenode02","text":"xinetd[4580]: START: mysql_status pid=939762 from=::ffff:10.108.196.205","label":"normal"}
{"timestamp":1748757215696,"host":"hivenode02","text":"xinetd[4580]: EXIT: mysql_status status=0 pid=2275839 duration=0(sec)","label":"normal"}
{"timestamp":1748757302898,"host":"hivenode02","text":"python: ---- **** -----","label":"normal"}
{"timestamp":1748758203986,"host":"hivenode02","text":"infinity[4139103]: an error occurred while requesting bindings <urlopen error [Errno 111] Connection refused>","label":"abnormal"}
{"timestamp":1748758206115,"host":"hivenode02","text":"systemd: Starting Session 2355169 of user root.","label":"normal"}
{"timestamp":1748759770413,"host":"hivenode02","text":"python: User information: uid=0 euid=0 gid=0 egid=0","label":"normal"}
{"timestamp":1748760406510,"host":"hivenode02","text":"python: \/usr\/lib\/python2.7\/site-packages\/celery\/platforms.py:796: RuntimeWarning: You're running the worker with superuser privileges: this is","label":"normal"}
{"timestamp":1748760844978,"host":"hivenode02","text":"xinetd[4580]: START: mysql_status pid=3106657 from=::ffff:10.108.196.204","label":"normal"}
{"timestamp":1748760891261,"host":"hivenode02","text":"xinetd[4580]: START: mysql_status pid=3156388 from=::ffff:10.108.196.205","label":"normal"}
{"timestamp":1748761135077,"host":"hivenode02","text":"systemd-logind: New session 2357032 of user root.","label":"normal"}
{"timestamp":1748761286790,"host":"hivenode02","text":"infinity[779724]: an error occurred while requesting bindings <urlopen error [Errno 111] Connection refused>","label":"abnormal"}
{"timestamp":1748762106137,"host":"hivenode02","text":"python: [tasks]","label":"normal"}
{"timestamp":1748762308887,"host":"hivenode02","text":"python: . infinity.task.tasks.infi_cluster","label":"normal"}
{"timestamp":1748763092071,"host":"hivenode02","text":"xinetd[4580]: START: zk_status pid=1999416 from=::ffff:10.108.196.202","label":"normal"}
{"timestamp":1748766297912,"host":"hivenode02","text":"systemd: Starting Session 2360383 of user root.","label":"normal"}
{"timestamp":1748768531718,"host":"hivenode02","text":"infinity[779724]: an error occurred while requesting bindings <urlopen error [Errno 111] Connection refused>","label":"abnormal"}
{"timestamp":1748768656636,"host":"hivenode02","text":"python: ---- **** -----","label":"normal"}
{"timestamp":1748770639464,"host":"hivenode02","text":"python: absolutely not recommended!","label":"normal"}
{"timestamp":1748770981387,"host":"hivenode02","text":"python: -------------- [queues]","label":"normal"}
{"timestamp":1748771265599,"host":"hivenode02","text":"systemd: Starting Session 2363605 of user root.","label":"normal"}
{"timestamp":1748771372230,"host":"hivenode02","text":"systemd: Starting Session 2363673 of user root.","label":"normal"}
{"timestamp":1748773044663,"host":"hivenode02","text":"python: -------------- celery@hivenode02 v4.2.1 (windowlicker)","label":"normal"}
{"timestamp":1748773492874,"host":"hivenode02","text":"python: - ** ---------- .> transport:   amqp:\/\/rabbitmq:**@10.0.100.105:5672\/\/","label":"normal"}
{"timestamp":1748774208318,"host":"hivenode02","text":"systemd: infi-celery.service holdoff time over, scheduling restart.","label":"normal"}
{"timestamp":1748774230269,"host":"hivenode02","text":"systemd-logind: New session 2365527 of user root.","label":"normal"}
{"timestamp":1748775931189,"host":"hivenode02","text":"xinetd[4580]: EXIT: mongo_status status=0 pid=3174854 duration=0(sec)","label":"normal"}
{"timestamp":1748776497925,"host":"hivenode02","text":"systemd: Starting Session 2366997 of user root.","label":"normal"}
{"timestamp":1748777764199,"host":"hivenode02","text":"xinetd[4580]: EXIT: zk_status status=0 pid=1554228 duration=0(sec)","label":"normal"}
{"timestamp":1748777800733,"host":"hivenode02","text":"python: -------------- [queues]","label":"normal"}
{"timestamp":1748778780678,"host":"hivenode02","text":"infinity[779724]: an error occurred while requesting bindings <urlopen error [Errno 111] Connection refused>","label":"abnormal"}
{"timestamp":1748778879674,"host":"hivenode02","text":"systemd: infi-celery.service: main process exited, code=exited, status=1\/FAILURE","label":"normal"}
{"timestamp":1748779574378,"host":"hivenode02","text":"python: .> node2            exchange=node2(direct) key=node2","label":"normal"}
{"timestamp":1748779862850,"host":"hivenode02","text":"bash: WARNING: 2025\/06\/01 20:11:02 grpc: Server.Serve failed to create ServerTransport:  connection error: desc = \"transport: http2Server.HandleStreams failed to read initial settings frame: read tcp 10.0.100.102:2379->10.0.100.104:64843: read: connection reset by peer\"","label":"abnormal"}
{"timestamp":1748781853609,"host":"hivenode02","text":"infinity[779724]: monitor net list is null","label":"normal"}
{"timestamp":1748782059237,"host":"hivenode02","text":"xinetd[4580]: EXIT: mysql_status status=0 pid=3325837 duration=1(sec)","label":"normal"}
{"timestamp":1748782930614,"host":"hivenode02","text":"systemd: Started Session 2371140 of user root.","label":"normal"}
{"timestamp":1748783758717,"host":"hivenode02","text":"systemd: Starting Session 2371672 of user root.","label":"normal"}
{"timestamp":1748784487856,"host":"hivenode02","text":"python: .> node2            exchange=node2(direct) key=node2","label":"normal"}
{"timestamp":1748784963120,"host":"hivenode02","text":"systemd-logind: New session 2372452 of user root.","label":"normal"}
{"timestamp":1748785501158,"host":"hivenode02","text":"xinetd[4580]: START: mysql_status pid=3952030 from=::ffff:10.108.196.204","label":"normal"}
{"timestamp":1748787081320,"host":"hivenode02","text":"xinetd[4580]: START: mongo_status pid=1966307 from=::ffff:10.108.196.204","label":"normal"}
{"timestamp":1748788217628,"host":"hivenode02","text":"python: .> infinity_queue   exchange=infinity_exchange(direct) key=infinity_queue","label":"normal"}
{"timestamp":1748788436073,"host":"hivenode02","text":"infinity[779724]: an error occurred while requesting bindings <urlopen error [Errno 111] Connection refused>","label":"abnormal"}
{"timestamp":1748788507113,"host":"hivenode02","text":"python: - ** ---------- .> app:         __main__:0x23dfa90","label":"normal"}
{"timestamp":1748789926453,"host":"hivenode02","text":"python: - ** ---------- [config]","label":"normal"}
{"timestamp":1748790245495,"host":"hivenode02","text":"systemd: infi-celery.service: control process exited, code=exited status=1","label":"normal"}
{"timestamp":1748790918963,"host":"hivenode02","text":"systemd: infi-celery.service: control process exited, code=exited status=1","label":"normal"}
{"timestamp":1748790997588,"host":"hivenode02","text":"xinetd[4580]: START: mysql_status pid=3236032 from=::ffff:10.108.196.201","label":"normal"}
{"timestamp":1748791286647,"host":"hivenode02","text":"python: \/usr\/lib\/python2.7\/site-packages\/celery\/platforms.py:796: RuntimeWarning: You're running the worker with superuser privileges: this is","label":"normal"}
{"timestamp":1748791453399,"host":"hivenode02","text":"infinity[779724]: an error occurred while requesting bindings <urlopen error [Errno 111] Connection refused>","label":"abnormal"}
{"timestamp":1748791503594,"host":"hivenode02","text":"xinetd[4580]: EXIT: mysql_status status=0 pid=3955429 duration=0(sec)","label":"normal"}
{"timestamp":1748792854970,"host":"hivenode02","text":"xinetd[4580]: EXIT: zk_status status=0 pid=1648874 duration=0(sec)","label":"normal"}
{"timestamp":1748793662041,"host":"hivenode02","text":"python: - ** ---------- .> transport:   amqp:\/\/rabbitmq:**@10.0.100.105:5672\/\/","label":"normal"}
{"timestamp":1748793790906,"host":"hivenode02","text":"systemd: Started Session 2378150 of user root.","label":"normal"}
{"timestamp":1748795465592,"host":"hivenode02","text":"systemd-logind: Removed session 2379230.","label":"normal"}
{"timestamp":1748795621584,"host":"hivenode02","text":"systemd-logind: Removed session 2379327.","label":"normal"}
{"timestamp":1748795939175,"host":"hivenode02","text":"systemd: infi-celery.service: main process exited, code=exited, status=1\/FAILURE","label":"normal"}
{"timestamp":1748797468206,"host":"hivenode02","text":"python: [tasks]","label":"normal"}
{"timestamp":1748798633822,"host":"hivenode02","text":"systemd: infi-celery.service holdoff time over, scheduling restart.","label":"normal"}
{"timestamp":1748800463667,"host":"hivenode02","text":"python: - ** ---------- .> results:     elasticsearch:\/\/10.0.100.105:8200\/infi_queue_result\/queue_result","label":"normal"}
{"timestamp":1748801033803,"host":"hivenode02","text":"xinetd[4580]: START: mysql_status pid=358341 from=::ffff:10.108.196.203","label":"normal"}
{"timestamp":1748801098218,"host":"hivenode02","text":"infinity[779724]: an error occurred while requesting bindings <urlopen error [Errno 111] Connection refused>","label":"abnormal"}
{"timestamp":1748801399479,"host":"hivenode02","text":"infinity[779724]: an error occurred while requesting bindings <urlopen error [Errno 111] Connection refused>","label":"abnormal"}
{"timestamp":1748801672161,"host":"hivenode02","text":"python: state:True","label":"normal"}
{"timestamp":1748802097005,"host":"hivenode02","text":"systemd: Started Session 2383501 of user root.","label":"normal"}
{"timestamp":1748802358146,"host":"hivenode02","text":"xinetd[4580]: START: mysql_status pid=2172398 from=::ffff:10.108.196.205","label":"normal"}
{"timestamp":1748802372380,"host":"hivenode02","text":"infinity[2177623]: an error occurred while requesting bindings <urlopen error [Errno 111] Connection refused>","label":"abnormal"}
{"timestamp":1748802611248,"host":"hivenode02","text":"systemd-logind: New session 2383835 of user root.","label":"normal"}
{"timestamp":1748802937745,"host":"hivenode02","text":"systemd-logind: Removed session 2384044.","label":"normal"}
{"timestamp":1748803765700,"host":"hivenode02","text":"kill: kill: cannot find process \"\"","label":"normal"}
{"timestamp":1748804113432,"host":"hivenode02","text":"python: .> node2            exchange=node2(direct) key=node2","label":"normal"}
{"timestamp":1748804156932,"host":"hivenode02","text":"python: - *** --- * --- .> concurrency: 4 (prefork)","label":"normal"}
{"timestamp":1748804757075,"host":"hivenode02","text":"systemd: Starting Infinity Celery Worker Service...","label":"normal"}
